-- MySQL Script generated by MySQL Workbench
-- 10/11/16 13:18:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema internet_of_things_workshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema internet_of_things_workshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `internet_of_things_workshop` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `internet_of_things_workshop` ;

-- -----------------------------------------------------
-- Table `internet_of_things_workshop`.`device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `internet_of_things_workshop`.`device` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internet_of_things_workshop`.`participant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `internet_of_things_workshop`.`participant` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `full_name` VARCHAR(45) NOT NULL COMMENT '',
  `profile_picture` VARCHAR(45) NULL COMMENT '',
  `device_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_participant_device1_idx` (`device_id` ASC)  COMMENT '',
  CONSTRAINT `fk_participant_device1`
    FOREIGN KEY (`device_id`)
    REFERENCES `internet_of_things_workshop`.`device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internet_of_things_workshop`.`entry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `internet_of_things_workshop`.`entry` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `timestamp` TIMESTAMP(10) NOT NULL COMMENT '',
  `participant_id` INT NOT NULL COMMENT '',
  `device_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_entry_participant_idx` (`participant_id` ASC)  COMMENT '',
  INDEX `fk_entry_device1_idx` (`device_id` ASC)  COMMENT '',
  CONSTRAINT `fk_entry_participant`
    FOREIGN KEY (`participant_id`)
    REFERENCES `internet_of_things_workshop`.`participant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entry_device1`
    FOREIGN KEY (`device_id`)
    REFERENCES `internet_of_things_workshop`.`device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
